language: go

go:
  - 1.7

#go_import_path: github.com/nimbleindustry/device

install: true

script:
  - cd $GOPATH
  - tree -d
  # go build -o device src/github.com/nimbleindustry/device/main.go
    
